# ==========================================
# Application
# ==========================================
spring.application.name=booking-service

# Active Profile
spring.profiles.active=dev

# ==========================================
# Actuator
# ==========================================
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

# ==========================================
# Application Information
# ==========================================
info.app.name=Travel Booking Microservice
info.app.version=1.0.0
info.app.description=Enterprise Spring Boot Microservice for Travel Booking Management
info.app.author=Srujana Gattu

# ==========================================
# Swagger / OpenAPI
# ==========================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html





